services:
  - type: web
    name: omxsgi-momentum
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DASHBOARD_USER
        value: admin
      - key: DASHBOARD_PASS
        value: password
